export const en = {
  appName: 'Enterprise HRMS',
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to continue to your workplace.',
  clientCodeTitle: 'Enter client code',
  clientCodeSubtitle: 'Load the right company workspace before employee login.',
  clientCodeLabel: 'Client code',
  multiClientReady: 'Multi-client workspace',
  clientBrandingHint: 'Client branding and policies load before login.',
  invalidClientCode: 'Invalid client code',
  invalidClientCodeMessage: 'Please enter an approved client code shared by your HR team.',
  selectedClient: 'Selected client',
  changeClient: 'Change',
  continue: 'Continue',
  employeeId: 'Employee ID or email',
  emailAddress: 'Email address',
  password: 'Password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  signIn: 'Sign in',
  biometricLogin: 'Login using biometrics',
  loginWithBiometric: 'Login with fingerprint or face',
  faceLogin: 'Login with Face Unlock',
  faceLoginTitle: 'Biometric login',
  faceLoginSubtitle: 'Use Face Unlock or Fingerprint to verify your identity.',
  faceEnrollmentTitle: 'Face registration',
  captureSelfie: 'Capture live selfie',
  mockLocationWarning:
    "Mock location detected. Kindly uninstall Fly GPS or any mock location app and disable mock location; otherwise you won't be able to login.",
  dashboard: 'Dashboard',
  attendance: 'Attendance',
  requests: 'Requests',
  profile: 'Profile',
  more: 'More',
  markAttendance: 'Mark attendance',
  online: 'Online',
  offline: 'Offline',
  syncing: 'Syncing...',
  lastSynced: 'Last synced',
  checkIn: 'Check in',
  checkOut: 'Check out',
  outsideOffice: 'You are outside office premises.',
  faceMismatch: 'Face verification failed.',
  retry: 'Retry',
  emptyState: 'No records available.',
  appLocked: 'App locked',
  unlock: 'Unlock securely',
  logout: 'Logout',
  back: 'Back',
  backToClientCode: 'Back to client code',
  backToLogin: 'Back to login',
  exitRegistrationMessage: 'Face registration is required to continue. Returning will securely log you out.',
  rememberMe: 'Remember email and password on this device',
  credentialsStoredSecurely: 'Saved securely on this device',
  openCamera: 'Open camera',
  closeCamera: 'Close camera',
  cameraStandby: 'Camera is off',
  cameraStandbyMessage: 'Open the camera only when you are ready to capture this photo.',
  secureHrms: 'Secure HRMS',
  locationIntegrityRequired: 'Location integrity required',
  mockLocationBlockedBeforeLogin: 'Mock location and Fly GPS apps are blocked before login.',
  invalidLogin: 'Invalid login',
  invalidLoginMessage: 'Please enter a valid email address and password.',
  biometricRequired: 'Biometric required',
  biometricRequiredLoginMessage:
    'Please configure Face Unlock or Fingerprint before login.',
  loginFailed: 'Login failed',
  passwordBiometricRequired: 'Face Unlock or Fingerprint verification is required after password.',
  securityCheckFailed: 'Security check failed',
  securityCheckFailedMessage: 'Please retry after enabling GPS and stable internet.',
  enableGps: 'Enable GPS',
  openGpsSettings: 'Open GPS settings',
  gpsRequiredTitle: 'GPS required',
  gpsRequiredMessage: 'Please enable Location/GPS to continue secure login or attendance.',
  gpsSettingsHint: 'Location appears to be off. Open settings, enable GPS, then return to HRMS.',
  networkUnavailable: 'No internet connection',
  networkUnavailableMessage: 'Connect to the internet and try again.',
  requestTimedOut: 'Request timed out',
  requestTimedOutMessage: 'The server did not respond in time. Please retry.',
  serverUnavailable: 'Service unavailable',
  serverUnavailableMessage: 'HRMS could not complete the request. Please try again shortly.',
  unexpectedLoginError: 'Login could not be completed. Please retry or contact HR support.',
  clientValidationUnavailable: 'Client validation unavailable',
  clientValidationUnavailableMessage: 'The client validation service is unavailable. Please try again shortly.',
  osBiometricAuthentication: 'OS biometric authentication',
  biometricLoginPanel:
    'The system biometric prompt verifies the enrolled phone user, so random selfies or photos cannot unlock HRMS.',
  noPhotoMatching: 'No photo matching on device',
  noPhotoMatchingCopy:
    'Real face matching should happen on the backend. This app uses OS biometric for reliable local identity checks.',
  authenticateAndLogin: 'Authenticate and login',
  registrationRequired: 'Registration required',
  registrationRequiredMessage: 'Please login with password and complete biometric registration first.',
  biometricLoginFailed: 'Biometric login failed',
  biometricLoginFailedMessage: 'Please retry after confirming your device biometric.',
  biometricLoginNotRegistered:
    'Biometric login is available only after first password login and device registration.',
  faceEnrollmentSubtitle:
    'Register front, slight left, and slight right face photos to enable secure attendance.',
  registerFace: 'Register face',
  faceNotRegistered: 'Not registered',
  faceRegisteredStatus: 'Registered',
  checkingFaceStatus: 'Checking',
  faceRegistrationRequiredForAttendance:
    'Register your face once before using check in or check out.',
  frontFace: 'Front',
  rightFace: 'Slight Right',
  leftFace: 'Slight Left',
  frontFaceTitle: 'Look straight at the camera',
  rightFaceTitle: 'Turn 15-30 degrees to your right',
  leftFaceTitle: 'Turn 15-30 degrees to your left',
  frontFaceInstruction: 'Keep your face centered with both eyes and your nose clearly visible.',
  rightFaceInstruction: 'Turn slightly right while keeping both eyes and your nose clearly visible.',
  leftFaceInstruction: 'Turn slightly left while keeping both eyes and your nose clearly visible.',
  captureFrontPhoto: 'Capture front photo',
  captureRightPhoto: 'Capture slight right photo',
  captureLeftPhoto: 'Capture slight left photo',
  allAnglesCaptured: 'All face angles captured',
  faceCaptureReady: 'Ready',
  faceCaptureReadyMessage: 'Review the photos below or submit secure registration.',
  faceCaptureIncomplete: 'Face capture incomplete',
  faceCaptureIncompleteMessage:
    'Please capture front, slight left, and slight right face photos before continuing.',
  submitFaceRegistration: 'Submit face registration',
  frontCameraRequired: 'Front camera permission is required.',
  securityPolicy: 'Security policy',
  faceEnrollmentPolicy:
    'These photos are attached to your employee ID and registered device. When live API is enabled, they are uploaded to HRMS for backend verification.',
  biometricEnrollmentNote: 'Device biometric confirmation is required before saving this first-login registration.',
  registerFaceAndContinue: 'Register biometric and continue',
  faceRegistered: 'Biometric registered',
  faceRegisteredMessage:
    'This is your first login. This device has been registered with your profile. You will not be able to log in from another device. To register a different device, please contact your HR.',
  registrationFailed: 'Registration failed',
  registrationFailedMessage: 'Please retry with clear lighting, biometrics enabled, and stable internet.',
  faceQualityRejected: 'Face capture not accepted',
  faceQualityRejectedMessage:
    'Keep only one face in frame with both eyes and the nose clearly visible, then retake the photos.',
  faceEnrollmentNetworkMessage:
    'Face registration could not reach the server. Check your connection and try again.',
  goodDay: 'Good day,',
  employeeIdShort: 'Employee ID',
  department: 'Department',
  todayAttendance: 'Today attendance',
  notMarked: 'Not marked',
  workingHours: 'Working hours',
  leaveBalance: 'Leave balance',
  pendingRequests: 'Pending requests',
  notifications: 'Notifications',
  quickActions: 'Quick actions',
  secureAttendance: 'Secure attendance',
  payslip: 'Payslip',
  payslipReady: 'June 2026 ready',
  directory: 'Directory',
  findEmployees: 'Find employees',
  upcomingHolidays: 'Upcoming holidays',
  companyAnnouncements: 'Company announcements',
  face: 'Face',
  location: 'Location',
  last7Days: 'Last 7 days',
  validatingAttendance: 'Validating selfie, location, and network state.',
  secureCheckIn: 'Secure check in',
  secureCheckOut: 'Secure check out',
  attendanceCaptureSubtitle:
    'Live selfie, GPS integrity, and office geofence are verified before attendance.',
  selfieAudit: 'Live selfie',
  backendCanVerifyFace: 'Selfie captured securely for attendance verification',
  faceModelRequiredTitle: 'Face verification unavailable',
  faceModelRequiredMessage:
    'Please register your face again or contact HR if attendance verification cannot continue.',
  preciseGps: 'Precise GPS',
  officeRadiusValidated: 'Office radius validated',
  mockGps: 'Mock GPS',
  flyGpsBlocked: 'Fly GPS blocked',
  captureAndMarkAttendance: 'Capture and mark attendance',
  attendanceSaved: 'Attendance saved',
  attendanceSavedMessage: 'Your live selfie and location were verified.',
  done: 'Done',
  internetRequired: 'Internet required',
  internetRequiredAttendance: 'Attendance requires an active internet connection.',
  locationPermissionDenied: 'Location permission denied',
  locationPermissionAttendance: 'Precise GPS is required for attendance.',
  outsideOfficeTitle: 'Outside office premises',
  biometricCancelled: 'Biometric cancelled',
  attendanceBiometricCancelled: 'Attendance cannot proceed without biometric confirmation.',
  attendanceFailed: 'Attendance failed',
  attendanceFailedMessage:
    'Please keep GPS on, face the camera clearly, and retry from office premises.',
  leaveManagement: 'Leave management',
  applyLeave: 'Apply leave',
  submitLeaveRequest: 'Submit leave request',
  leaveHistory: 'Leave history',
  noLeaveRequests: 'No leave requests submitted yet.',
  otherRequests: 'Other requests',
  createAndTrack: 'Create and track',
  leaveSubmitted: 'Leave submitted',
  leaveSubmittedMessage: 'Your leave request has been sent for approval.',
  leaveRequestFailed: 'Leave request failed',
  leaveInvalidDates: 'Please enter dates in YYYY-MM-DD format.',
  leaveInvalidRange: 'To date cannot be before from date.',
  leaveReasonRequired: 'Please enter a clear reason with at least 3 characters.',
  leaveInsufficientBalance: 'You do not have enough paid leave balance for this request.',
  sessionExpired: 'Your session expired. Please login again.',
  leaveGenericFailure: 'Leave request could not be submitted. Please retry.',
  fromDate: 'From date (YYYY-MM-DD)',
  toDate: 'To date (YYYY-MM-DD)',
  reason: 'Reason',
  modules: 'Modules',
  settings: 'Settings',
  darkMode: 'Dark mode',
  privacyPolicy: 'Privacy Policy',
  terms: 'Terms',
  version: 'Version',
  logoutTitle: 'Logout',
  logoutMessage: 'You will need to sign in again to access HRMS.',
  cancel: 'Cancel',
  appLockBody: 'Authenticate with fingerprint, face unlock, or device password.',
  employeeInformation: 'Employee information',
  email: 'Email',
  reportingManager: 'Reporting manager',
  emergencyContact: 'Emergency contact',
  skillsAndDocuments: 'Skills and documents',
  skills: 'Skills',
  skillsValue: 'HR operations, employee engagement, compliance',
  education: 'Education',
  educationValue: 'MBA Human Resources',
  experience: 'Experience',
  experienceValue: '7 years',
  documents: 'Documents',
  documentsValue: 'Offer letter, appointment letter, policies',
};
